# Generated by Django 5.1 on 2024-09-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='страна')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='страна')),
                ('house_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='номер дома')),
                ('type', models.CharField(choices=[('factory', 'Завод'), ('store', 'розничный магазин'), ('SP', 'ИП')], max_length=50, verbose_name='тип компании')),
                ('level', models.CharField(choices=[(0, 'нулевой уровень иерархии'), (1, 'первый уровень иерархии'), (2, 'второй уровень иерархии')], max_length=10, verbose_name='уровень иерархии')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='долг перед поставщиком (в рублях)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='название')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='модель продукта')),
                ('release_date', models.DateField(verbose_name='дата выхода на рынок')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
