# Generated by Django 5.1 on 2024-09-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата выхода на рынок'),
        ),
    ]
