# Generated by Django 5.1 on 2024-09-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_product_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_supplier', to='companies.company', verbose_name='поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='companies.company', verbose_name='компания'),
        ),
    ]
