# Generated by Django 5.1 on 2024-09-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_supplier_alter_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='улица'),
        ),
    ]
