# Generated by Django 5.1 on 2024-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_city_alter_company_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('factory', 'завод'), ('store', 'розничный магазин'), ('SP', 'ИП')], max_length=50, verbose_name='тип компании'),
        ),
    ]
