# Generated by Django 5.1 on 2024-09-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='level',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2)], max_length=10, verbose_name='уровень иерархии'),
        ),
    ]
