# Generated by Django 5.1 on 2024-09-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name', 'country'), 'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
